#!/bin/bash

apt-get update
apt-get install git curl sudo -y
curl -sL https://deb.nodesource.com/setup_6.x | sudo bash -
apt-get -y install python build-essential nodejs

npm install pm2 -g
cd /home/ubuntu/
git clone git://github.com/dgabrielli76/sort-back.git
cd sort-back
npm install .
ulimit -n 102400
PORT=80 NODE_ENV=production pm2 start index.js
